name: vetti_flow_1_0
description: "VettiFlow Flutter App - interface para fluxo de producao."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_bloc: ^9.1.0
  intl: ^0.20.2
  provider: ^6.1.5
  web: ^1.1.1
  http: ^1.6.0
  pdf: ^3.13.1
  printing: ^5.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/vetti-flow-logo.png
    - assets/fonts/IBMPlexSans-Regular.ttf
    - assets/fonts/IBMPlexSans-SemiBold.ttf
    - assets/fonts/OFL.txt
